### ISSUE TITLE
Figure out what we are selling?

### ISSUE THREAD

**Issue by djsharkey** [Serghar/DSP#21]
.....

**Comment by samueljcoronado** [comment]
Some possibilities looking at the Unsplash stock photos:

Cameras: https://unsplash.com/search?utf8=%E2%9C%93&keyword=camera&button=
Writing utensils (pens, pencils, typewriters, journals/notebooks): https://unsplash.com/search?utf8=%E2%9C%93&keyword=writing&button=
Shoes?: https://unsplash.com/search?utf8=%E2%9C%93&keyword=shoes&button=
Art/photography

**Comment by lilpkstud** [comment]
SHOES
